# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6107a30cafdee6eea905101d829d16cb42a7194106b5c2f9f1414410a3520ebbf6994f8fd8b5be7fc4d80ecf5b92cddb54195728d9963d8b93b6e59e309f9eae

test:
  secret_key_base: 696c7db1c54818f5f9569820285db634a7407c9030f11b838eb565e78dade80c5c41789dc701f631fbfee3255fc71f733e46be47b9947862e7e1902973949292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
